### ISSUE TITLE
example does not build

### ISSUE THREAD

**Issue by Be-ing** [udoprog/audio#2]
```
audio on  main via 🦀 v1.58.0 
❯ cargo build
    Updating crates.io index
    Updating git repository `https://github.com/udoprog/minimp3-rs`
    Updating git submodule `https://github.com/lieff/minimp3.git`
    Updating git repository `https://github.com/udoprog/rubato`
error: no matching package named `audio` found
location searched: https://github.com/udoprog/rubato?branch=next#4ca6e6f9
required by package `rubato v0.9.0 (https://github.com/udoprog/rubato?branch=next#4ca6e6f9)`
    ... which satisfies git dependency `rubato` of package `examples v0.0.0 (/home/be/sw/audio/examples)`
```
The examples [use your fork of rubato](https://github.com/udoprog/audio/blob/main/examples/Cargo.toml#L13) which [uses relative filesystem paths for audio](https://github.com/udoprog/rubato/blob/next/Cargo.toml#L26). While that may work on your machine, it does not work on mine. I recommend to use [`patch.crates-io`](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section) in ~/.cargo/config.toml to work on libraries locally so you don't accidentally commit Cargo.toml in the repository with relative paths specific to your machine.

I see you have [made some contributions to rubato](https://github.com/HEnquist/rubato/pulls?q=is%3Apr+author%3Audoprog+) but the branch used by the example uses a [pretty big change](https://github.com/udoprog/rubato/commit/4ca6e6f9f0f0d2b0498361b7290262c491fb3f24) that is not upstream nor do I see a PR for it upstream. Were you intending to make a PR for that upstream?

**Comment by udoprog** [comment]
Yeah. This is just for experimentation. I don't intend to submit anything upstream until this crate is done. I elaborated more in #3. But, we can certainly make it easier to build the rubato branch by not using relative paths!

**Comment by udoprog** [comment]
Example should now build, and they've been reconfigured so that they shouldn't break as easily. They now depend on the git version of the crate rather than a published one.
