### ISSUE TITLE
Are audio software patterns in scope for this crate?

### ISSUE THREAD

**Issue by berkus** [udoprog/audio#37]
The name audio is so generic that I was wondering if implementation of some of [Data-flow Patterns Catalog](https://amatria.in/pubs/plop2006.pdf) makes sense?

Talking specifically about chapter 7 Multiple-Window Circular Buffer and chapter 8 Phantom Buffer, as mostly applicable to sample munching.

**Comment by udoprog** [comment]
I personally don't consider it in scope unless it's used to enable fundamental audio interchange. Routing, porting, and buffering associated with it might be too high level.

But there's no hard and fast rules.

**Comment by berkus** [comment]
Got it, thanks!
